version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"  # Expose frontend on port 8080

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"  # Expose backend on port 3000
    depends_on:
      - database

  database:
    image: nouchka/sqlite3
    volumes:
      - ./database:/database
    environment:
      - DB_PATH=/database/database.db
