version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"  # Expose frontend on port 8080

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"  # Expose backend on port 3000
    volumes:
      - ./database:/app/database  # Mount the local database directory to the container
    environment:
      - DB_HOST=database  # This should match the service name of your PostgreSQL container
      - DB_USER=your-user
      - DB_PASSWORD=your-password
      - DB_NAME=your-db
    depends_on:
      - database  # Ensure backend starts after the database is ready

  database:
    image: postgres:latest  # Use the official PostgreSQL image
    environment:
      POSTGRES_USER: your-user  # Database user
      POSTGRES_PASSWORD: your-password  # Database password
      POSTGRES_DB: your-db  # Database name
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres_data:  # Named volume to persist PostgreSQL data
