name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  # Frontend and Backend Tests
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Frontend Tests
    - name: Set up Node.js for Frontend
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies for Frontend
      run: npm install
      working-directory: ./frontend

    - name: Wait for frontend to be ready
      run: |
        timeout=30
        until curl -s http://localhost:8080 > /dev/null; do
          echo "Waiting for frontend to be ready..."
          sleep 2
          timeout=$((timeout-1))
          if [ $timeout -le 0 ]; then
            echo "Frontend server failed to start."
            exit 1
          fi
        done
    - name: Run tests for Frontend
      run: npm run test
      working-directory: ./frontend

    # Backend Tests
    - name: Set up Node.js for Backend
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies for Backend
      run: npm install
      working-directory: ./backend

    - name: Run tests for Backend
      run: npm run test
      working-directory: ./backend

  # Build and Push Backend Docker Image
  build-backend:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub for Backend
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Backend Docker image
      run: |
        docker build -t yourusername/backend:latest ./backend

    - name: Push Backend Docker image
      run: |
        docker push yourusername/backend:latest

  # Build and Push Frontend Docker Image
  build-frontend:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub for Frontend
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Frontend Docker image
      run: |
        docker build -t yourusername/frontend:latest ./frontend

    - name: Push Frontend Docker image
      run: |
        docker push yourusername/frontend:latest
