name: Test Frontend Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # test-frontend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Step 1: Checkout the code
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     # Step 2: Setup Node.js
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '16'

  #     # Step 3: Install system dependencies for Cypress
  #     - name: Install system dependencies for Cypress
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y \
  #         xvfb libgtk2.0-0 libgtk-3-0 \
  #         libnotify-dev libgconf-2-4 libnss3 \
  #         libxss1 libasound2 libxtst6 \
  #         xauth dbus libgbm-dev \
  #         x11-utils

  #     # Step 4: Install frontend dependencies
  #     - name: Install frontend dependencies
  #       run: npm install
  #       working-directory: ./frontend

  #     # Step 5: Start Xvfb (virtual display for Cypress)
  #     - name: Start Xvfb (virtual display)
  #       run: Xvfb :99 -ac -screen 0 1920x1080x24 &
  #       env:
  #         DISPLAY: :99

  #     # Step 6: Start DBus
  #     - name: Start DBus (without systemd)
  #       run: |
  #         sudo mkdir -p /run/dbus
  #         sudo dbus-daemon --system --fork

  #     # Step 7: Run Cypress tests
  #     - name: Run Cypress tests
  #       env:
  #         DISPLAY: :99  # Set the virtual display for Cypress
  #       run: npm run cypress:run
  #       working-directory: ./frontend

  # test-backend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '16'

  #     - name: Install dependencies
  #       run: npm install
  #       working-directory: ./backend

  #     - name: Run tests
  #       run: npm test
  #       working-directory: ./backend
  #       env:
  #         NODE_ENV: test

  build-backend-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t erekysy/backendmicroservicecicd:latest ./backend
  
  build-frontend-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t erekysy/frontendmicroservicecicd:latest ./frontend